Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.

In [ ]:
# Code here
import numpy as np

array_1D = np.array([1,2,3,4,5,6])

array_2D = array_1D.reshape(2,3)

print(array_2D)



[[1 2 3]
 [4 5 6]]


Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix

In [ ]:
# Code here

array_3x3 = np.array([[1,2,3,],[4,5,6],[7,8,9]])

array_3x2 = np.array([[1,2,3],[4,5,6]])

results = np.dot(array_3x2 , array_3x3)
print(results)



[[30 36 42]
 [66 81 96]]


Write a NumPy program to find the most frequent value and the number of times it occured in the array


[

    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]  
 ]

In [ ]:
# Code here
import numpy as np

array = np.array = ([[1, 2, 3, 2, 1],[4, 2, 5, 2, 6],[2, 1, 2, 3, 2],[7, 2, 8, 2, 9]])
array

values, counts = np.unique(array, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
frequency = counts[np.argmax(counts)]

print(f"The most frequent value is {most_frequent_value} and it occurred {frequency} times.")

The most frequent value is 2 and it occurred 9 times.


Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.

[  [ 1.  2. nan  4.  5.],

 [ 6. nan  8.  9. 10.],

 [11. 12. 13. nan 15.],

 [16. 17. nan 19. 20.],

 [nan 22. 23. 24. 25.]  ]

In [72]:
# Code here
import numpy as np

nan = 0

array = np.array = ([[ 1, 2, nan, 4, 5,],[ 6, nan, 8, 9, 10],[11, 12, 13, nan, 15,],[16, 17, nan, 19, 20],[nan, 22, 23, 24, 25]])

nan = np.mean(array, axis = 1)

split_nan = np.split(nan,[1,2,3,4])

index = 1

# new_array = np.insert(array, index, nan, axis=1)

split_nan


[array([2.4]), array([6.6]), array([10.2]), array([14.4]), array([18.8])]

Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.

np.array([

    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
]

In [ ]:
# Code here